
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar';
import Navbar from '@/components/Navbar';
import SessionAuthProvider from '@/context/SessionAuthProvider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionAuthProvider>
      <div className='flex flex-col md:flex-row'>
          <Sidebar />
                   <div className='flex-1 '>
                   <Navbar />
 
            {children}
          </div>

        </div>
        </SessionAuthProvider>
      </body>
    </html>
  )
}
